name: Update Related PRs with Design Docs

on:
  pull_request:
    types: [closed]
    branches:
      - main
      - develop
      - develop/*
      - release/*
      - hotfix/*

jobs:
  update-design-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Merged PR Details
        id: get_pr_details
        uses: actions/github-script@v7
        with:
          script: |
            async function getMergedPRDetails() {
              try {
                console.log('=== GETTING PR DETAILS ===');
                
                // contextオブジェクトの存在確認
                if (typeof context === 'undefined') {
                  console.error('context object is undefined');
                  core.setFailed('context object is not available');
                  return;
                }
                
                // 複数の方法でPRオブジェクトを取得
                let pr = null;
                
                // 方法1: context.payload.pull_request (推奨)
                if (context.payload && context.payload.pull_request) {
                  pr = context.payload.pull_request;
                  console.log('Using context.payload.pull_request');
                }
                // 方法2: github.event.pull_request (フォールバック)
                else if (github.event && github.event.pull_request) {
                  pr = github.event.pull_request;
                  console.log('Using github.event.pull_request');
                }
                // 方法3: APIを使用してPRを取得
                else {
                  console.log('PR object not found in event, trying to get from API');
                  try {
                    const prNumber = context.issue.number;
                    if (!prNumber) {
                      throw new Error('PR number not found in context');
                    }
                    const { data: prData } = await github.rest.pulls.get({
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      pull_number: prNumber,
                    });
                    pr = prData;
                    console.log('Retrieved PR from API');
                  } catch (error) {
                    console.error('Failed to get PR from API:', error);
                    core.setFailed('Could not retrieve pull request information');
                    return;
                  }
                }
                
                if (!pr) {
                  console.error('Pull request object not found');
                  core.setFailed('Pull request object is undefined');
                  return;
                }
                
                const prBody = pr.body || '';
                const baseBranch = pr.base.ref;
                const headBranch = pr.head.ref;
                
                console.log('PR Number:', pr.number);
                console.log('PR Body Length:', prBody.length);
                console.log('Base Branch:', baseBranch);
                console.log('Head Branch:', headBranch);
                console.log('PR Merged:', pr.merged);
                
                // マージされていない場合は処理をスキップ
                if (!pr.merged) {
                  console.log('PR is not merged. Skipping processing.');
                  core.setOutput('design_docs', JSON.stringify([]));
                  core.setOutput('base_branch', baseBranch);
                  core.setOutput('head_branch', headBranch);
                  core.setOutput('merged_pr_number', pr.number.toString());
                  return;
                }
                
                // 設計書一覧セクションを正規表現で抽出
                console.log('=== DESIGN DOC EXTRACTION DEBUG ===');
                console.log('Looking for design doc section...');
                
                // 複数のパターンを試す
                let docSectionMatch = null;
                const patterns = [
                  /##\s*[^\r\n]*設計書一覧\r?\n([\s\S]*?)(?=\r?\n##|\r?\n---|$)/,
                  /#\s*[^\r\n]*設計書一覧\r?\n([\s\S]*?)(?=\r?\n#|\r?\n---|$)/,
                  /設計書一覧\r?\n([\s\S]*?)(?=\r?\n##|\r?\n#|\r?\n---|$)/
                ];
                
                for (let i = 0; i < patterns.length; i++) {
                  const pattern = patterns[i];
                  console.log(`Trying pattern ${i + 1}:`, pattern);
                  docSectionMatch = prBody.match(pattern);
                  if (docSectionMatch) {
                    console.log(`Pattern ${i + 1} matched!`);
                    break;
                  }
                }
                
                console.log('docSectionMatch:', docSectionMatch);
                
                let designDocs = [];
                
                if (docSectionMatch) {
                  console.log('Found design doc section:', docSectionMatch[1]);
                  
                  // 設計書セクションの内容を詳しく確認
                  console.log('=== DESIGN DOC SECTION DEBUG ===');
                  console.log('Section content length:', docSectionMatch[1].length);
                  const sectionLines = docSectionMatch[1].split('\n');
                  console.log('Section lines count:', sectionLines.length);
                  
                  // リンク抽出のデバッグ
                  console.log('=== LINK EXTRACTION DEBUG ===');
                  const linkPattern = /\*\s*\[.*?\]\(https:\/\/docs\.google\.com\/spreadsheets\/d\/.*?\)/g;
                  console.log('Looking for links with pattern:', linkPattern);
                  
                  const links = docSectionMatch[1].match(linkPattern);
                  console.log('Found links:', links);
                  
                  if (links) {
                    designDocs = links.map(link => link.trim());
                    console.log('Processed design docs:', designDocs);
                  } else {
                    console.log('No links found in section');
                    
                    // 代替パターンを試す
                    console.log('Trying alternative link patterns...');
                    
                    // パターン1: より緩いマッチング
                    const altPattern1 = /\*.*?https:\/\/docs\.google\.com\/spreadsheets\/d\/.*?\)/g;
                    const altLinks1 = docSectionMatch[1].match(altPattern1);
                    console.log('Alternative pattern 1 result:', altLinks1);
                    
                    // パターン2: 行単位でGoogleスプレッドシートのリンクを探す
                    const googleSheetLines = sectionLines.filter(line => line.includes('docs.google.com/spreadsheets'));
                    console.log('Lines containing Google Sheets links:', googleSheetLines);
                  }
                } else {
                  console.log('No design doc section found');
                  // 代替パターンを試す
                  console.log('Trying alternative patterns...');
                  
                  // パターン1: より緩いマッチング
                  const altMatch1 = prBody.match(/#\s*設計書一覧[\s\S]*?(?=\r?\n#|\r?\n---|$)/);
                  console.log('Alternative pattern 1 result:', altMatch1);
                  
                  if (altMatch1) {
                    console.log('Using alternative pattern result');
                    // 代替パターンで見つかった場合のリンク抽出
                    const links = altMatch1[0].match(/\*\s*\[.*?\]\(https:\/\/docs\.google\.com\/spreadsheets\/d\/.*?\)/g);
                    if (links) {
                      designDocs = links.map(link => link.trim());
                      console.log('Found links from alternative pattern:', designDocs);
                    }
                  } else {
                    // パターン2: 行単位での検索
                    const lines = prBody.split('\n');
                    console.log('Total lines in PR body:', lines.length);
                    
                    // パターン3: 設計書一覧を含む行を探す
                    const designDocLines = lines.filter(line => line.includes('設計書一覧'));
                    console.log('Lines containing "設計書一覧":', designDocLines.length);
                  }
                }
                
                console.log('Extracted Design Docs:', designDocs);
                console.log('Base Branch of Merged PR:', baseBranch);
                core.setOutput('design_docs', JSON.stringify(designDocs));
                core.setOutput('base_branch', baseBranch);
                core.setOutput('head_branch', headBranch);
                core.setOutput('merged_pr_number', pr.number.toString());
                
              } catch (error) {
                console.error('Error in Get Merged PR Details:', error);
                console.error('Error stack:', error.stack);
                core.setFailed('Failed to get PR details: ' + error.message);
              }
            }
            
            await getMergedPRDetails();

      - name: Find All Open PRs to the Same Base Branch
        id: find_all_open_prs
        uses: actions/github-script@v7
        with:
          script: |
            async function findOpenPRs() {
              try {
                console.log('=== FINDING OPEN PRS ===');
                
                const baseBranch = core.getInput('base_branch') || process.env.base_branch;
                const mergedPrNumber = core.getInput('merged_pr_number') || process.env.merged_pr_number;
                const headBranch = core.getInput('head_branch') || process.env.head_branch;
                
                console.log('Base Branch:', baseBranch);
                console.log('Head Branch:', headBranch);
                console.log('Merged PR Number:', mergedPrNumber);
                
                if (!headBranch) {
                  console.error('Head branch not provided');
                  core.setFailed('Head branch is required');
                  return;
                }
                
                // マージされたPRのヘッドブランチに向けられたオープンなPRを取得
                const { data: openPRs } = await github.rest.pulls.list({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  state: 'open',
                  head: `${context.repo.owner}:${headBranch}`,
                  sort: 'created',
                  direction: 'desc'
                });
                
                console.log('Found open PRs targeting head branch:', openPRs.length);
                
                // マージされたPRを除外
                const targetPRs = openPRs.filter(pr => pr.number != mergedPrNumber);
                
                console.log('Target PRs (excluding merged PR):', targetPRs.length);
                targetPRs.forEach(pr => {
                  console.log(`- PR #${pr.number}: ${pr.title} (base: ${pr.base.ref}, head: ${pr.head.ref})`);
                });
                
                const targetPrNumbers = targetPRs.map(pr => pr.number);
                core.setOutput('target_pr_numbers', JSON.stringify(targetPrNumbers));
                
              } catch (error) {
                console.error('Error in Find Open PRs:', error);
                console.error('Error stack:', error.stack);
                core.setFailed('Failed to find open PRs: ' + error.message);
              }
            }
            
            await findOpenPRs();
        env:
          base_branch: ${{ steps.get_pr_details.outputs.base_branch }}
          head_branch: ${{ steps.get_pr_details.outputs.head_branch }}
          merged_pr_number: ${{ steps.get_pr_details.outputs.merged_pr_number }}

      - name: Update Target PR Descriptions
        if: steps.find_all_open_prs.outputs.target_pr_numbers != '[]' && steps.find_all_open_prs.outputs.target_pr_numbers != 'null'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            async function updatePRDescriptions() {
              try {
                console.log('=== UPDATING PR DESCRIPTIONS ===');
                
                const targetPrNumbersStr = core.getInput('target_pr_numbers') || process.env.target_pr_numbers || '[]';
                const designDocsStr = core.getInput('design_docs') || process.env.design_docs || '[]';
                
                const targetPrNumbers = JSON.parse(targetPrNumbersStr);
                const designDocs = JSON.parse(designDocsStr);
                
                console.log('Target PR Numbers:', targetPrNumbers);
                console.log('Design Docs:', designDocs);
                
                if (!Array.isArray(targetPrNumbers) || targetPrNumbers.length === 0) {
                  console.log('No target PRs to update');
                  return;
                }
                
                if (!Array.isArray(designDocs) || designDocs.length === 0) {
                  console.log('No design docs to add');
                  return;
                }
                
                // 設計書セクションのテンプレートを作成
                const designDocSection = `\n\n## 関連設計書\n\n${designDocs.join('\n')}`;
                
                let successCount = 0;
                let errorCount = 0;
                
                for (const prNumber of targetPrNumbers) {
                  try {
                    console.log(`Updating PR #${prNumber}...`);
                    
                    // PRの現在の内容を取得
                    const { data: pr } = await github.rest.pulls.get({
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      pull_number: prNumber
                    });
                    
                    let newBody = pr.body || '';
                    
                    // 既に設計書セクションがあるかチェック
                    if (newBody.includes('## 関連設計書')) {
                      console.log(`PR #${prNumber} already has design doc section, skipping`);
                      continue;
                    }
                    
                    // 設計書セクションを追加
                    newBody += designDocSection;
                    
                    // PRの説明を更新
                    await github.rest.pulls.update({
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      pull_number: prNumber,
                      body: newBody
                    });
                    
                    console.log(`Successfully updated PR #${prNumber}`);
                    successCount++;
                    
                  } catch (error) {
                    console.error(`Error updating PR #${prNumber}:`, error.message);
                    errorCount++;
                    // 個別のPRの更新エラーは全体の処理を停止させない
                  }
                }
                
                console.log(`PR description updates completed. Success: ${successCount}, Errors: ${errorCount}`);
                
                if (errorCount > 0) {
                  console.warn(`Warning: ${errorCount} PR(s) failed to update`);
                }
                
              } catch (error) {
                console.error('Error in Update PR Descriptions:', error);
                console.error('Error stack:', error.stack);
                core.setFailed('Failed to update PR descriptions: ' + error.message);
              }
            }
            
            await updatePRDescriptions();
        env:
          target_pr_numbers: ${{ steps.find_all_open_prs.outputs.target_pr_numbers }}
          design_docs: ${{ steps.get_pr_details.outputs.design_docs }}