name: Update Related PRs with Design Docs

on:
  pull_request:
    types: [closed]
    branches:
      - main
      - develop
      - develop/*
      - release/*
      - hotfix/*

jobs:
  update-design-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Merged PR Details
        id: get_pr_details
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            
            // スクリプトファイルを読み込み
            const scriptPath = path.join(process.cwd(), 'scripts', 'update-design-docs.js');
            const scriptContent = fs.readFileSync(scriptPath, 'utf8');
            
            // グローバルオブジェクトを明示的に渡す
            const scriptFunction = new Function('core', 'github', 'context', scriptContent);
            
            // スクリプトを実行
            const { getMergedPRDetails } = scriptFunction(core, github, context);
            await getMergedPRDetails();

      - name: Find All Open PRs to the Same Base Branch
        id: find_all_open_prs
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            
            // スクリプトファイルを読み込み
            const scriptPath = path.join(process.cwd(), 'scripts', 'update-design-docs.js');
            const scriptContent = fs.readFileSync(scriptPath, 'utf8');
            
            // グローバルオブジェクトを明示的に渡す
            const scriptFunction = new Function('core', 'github', 'context', scriptContent);
            
            // スクリプトを実行
            const { findOpenPRs } = scriptFunction(core, github, context);
            await findOpenPRs();
        env:
          base_branch: ${{ steps.get_pr_details.outputs.base_branch }}
          merged_pr_number: ${{ steps.get_pr_details.outputs.merged_pr_number }}

      - name: Update Target PR Descriptions
        if: steps.find_all_open_prs.outputs.target_pr_numbers != '[]'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const path = require('path');
            
            // スクリプトファイルを読み込み
            const scriptPath = path.join(process.cwd(), 'scripts', 'update-design-docs.js');
            const scriptContent = fs.readFileSync(scriptPath, 'utf8');
            
            // グローバルオブジェクトを明示的に渡す
            const scriptFunction = new Function('core', 'github', 'context', scriptContent);
            
            // スクリプトを実行
            const { updatePRDescriptions } = scriptFunction(core, github, context);
            await updatePRDescriptions();
        env:
          target_pr_numbers: ${{ steps.find_all_open_prs.outputs.target_pr_numbers }}
          design_docs: ${{ steps.get_pr_details.outputs.design_docs }}