name: Update Related PRs with Design Docs

on:
  pull_request:
    types: [closed]
    branches:
      # 設計書リンクを共有したいPRのベースブランチを指定します。
      # 例: 'main', 'develop', 'release/*' など、運用に合わせて追加・変更してください。
      - main
      - develop
      - develop/*
      - release/*
      - hotfix/*

jobs:
  update-design-docs:
    # 一時的に条件を緩和してデバッグ
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # PRの更新に必要なパーミッション

    steps:
      - name: Debug Event Object
        uses: actions/github-script@v7
        with:
          script: |
            try {
              console.log('=== DEBUG INFORMATION ===');
              console.log('github object exists:', typeof github !== 'undefined');
              console.log('github.event exists:', typeof github.event !== 'undefined');
              
              if (typeof github !== 'undefined') {
                console.log('github.event_name:', github.event_name || 'undefined');
                console.log('github.event.action:', github.event.action || 'undefined');
                
                if (typeof github.event !== 'undefined') {
                  console.log('github.event keys:', Object.keys(github.event));
                  console.log('Full event object:', JSON.stringify(github.event, null, 2));
                  
                  // pull_requestオブジェクトの存在確認
                  if (github.event.pull_request) {
                    console.log('Pull request object exists');
                    console.log('PR number:', github.event.pull_request.number);
                    console.log('PR merged:', github.event.pull_request.merged);
                  } else {
                    console.log('Pull request object is undefined');
                  }
                } else {
                  console.log('github.event is undefined');
                }
              } else {
                console.log('github object is undefined');
              }
              
              // contextオブジェクトの確認
              console.log('context object exists:', typeof context !== 'undefined');
              if (typeof context !== 'undefined') {
                console.log('context.payload exists:', typeof context.payload !== 'undefined');
                if (typeof context.payload !== 'undefined') {
                  console.log('context.payload keys:', Object.keys(context.payload));
                }
              }
              
            } catch (error) {
              console.error('Error in debug step:', error);
              console.error('Error stack:', error.stack);
            }

      - name: Get Merged PR Details
        id: get_pr_details
        uses: actions/github-script@v7
        with:
          script: |
            try {
              console.log('=== GETTING PR DETAILS ===');
              
              // githubオブジェクトの存在確認
              if (typeof github === 'undefined') {
                console.error('github object is undefined');
                core.setFailed('github object is not available');
                return;
              }
              
              // 複数の方法でPRオブジェクトを取得
              let pr = null;
              
              // 方法1: github.event.pull_request
              if (github.event && github.event.pull_request) {
                pr = github.event.pull_request;
                console.log('Using github.event.pull_request');
              }
              // 方法2: context.payload.pull_request
              else if (context && context.payload && context.payload.pull_request) {
                pr = context.payload.pull_request;
                console.log('Using context.payload.pull_request');
              }
              // 方法3: APIを使用してPRを取得
              else {
                console.log('PR object not found in event, trying to get from API');
                try {
                  const prNumber = context.issue.number;
                  const { data: prData } = await github.rest.pulls.get({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    pull_number: prNumber,
                  });
                  pr = prData;
                  console.log('Retrieved PR from API');
                } catch (error) {
                  console.error('Failed to get PR from API:', error);
                  core.setFailed('Could not retrieve pull request information');
                  return;
                }
              }
              
              if (!pr) {
                console.error('Pull request object not found');
                core.setFailed('Pull request object is undefined');
                return;
              }
              
              const prBody = pr.body || ''; // マージされたPRの説明文を取得
              const baseBranch = pr.base.ref; // マージされたPRのベースブランチを取得
              
              console.log('PR Number:', pr.number);
              console.log('PR Body:', prBody);
              console.log('Base Branch:', baseBranch);
              
              // 設計書一覧セクションを正規表現で抽出
              // `# 設計書一覧` の後から、次の `#` 見出しまたはPRの終わりまでを対象とします。
              const docSectionMatch = prBody.match(/#\s*設計書一覧\n([\s\S]*?)(?=\n#|\n---|$)/);
              
              let designDocs = [];
              if (docSectionMatch && docSectionMatch[1]) {
                  // Googleスプレッドシートのリンク（`* [タイトル](https://docs.google.com/spreadsheets/d/...)` 形式）を抽出
                  const links = docSectionMatch[1].match(/\*\s*\[.*?\]\(https:\/\/docs\.google\.com\/spreadsheets\/d\/.*?\)/g);
                  if (links) {
                      designDocs = links.map(link => link.trim());
                  }
              }
              
              console.log('Extracted Design Docs:', designDocs);
              console.log('Base Branch of Merged PR:', baseBranch);
              core.setOutput('design_docs', JSON.stringify(designDocs));
              core.setOutput('base_branch', baseBranch);
              core.setOutput('merged_pr_number', pr.number); // マージされたPR自身の番号
              
            } catch (error) {
              console.error('Error in Get Merged PR Details:', error);
              console.error('Error stack:', error.stack);
              core.setFailed('Failed to get PR details: ' + error.message);
            }

      - name: Find All Open PRs to the Same Base Branch
        id: find_all_open_prs
        uses: actions/github-script@v7
        with:
          script: |
            const baseBranch = process.env.base_branch;
            const mergedPrNumber = parseInt(process.env.merged_pr_number);

            if (!baseBranch) {
              console.log('Base branch not found. Skipping finding open PRs.');
              core.setOutput('target_pr_numbers', JSON.stringify([]));
              return;
            }

            // マージされたPRと同じベースブランチをターゲットとする、オープンなすべてのPRを取得
            const { data: pulls } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open', // オープンなPRのみ
              base: baseBranch, // マージされたPRと同じベースブランチ
              per_page: 100 // 一度に取得するPRの最大数（必要に応じて調整）
            });
            
            // マージされたPR自身は更新対象から除外
            const targetPrNumbers = pulls
              .filter(pr => pr.number !== mergedPrNumber)
              .map(pr => pr.number);
            
            console.log('Found Open PR Numbers to update:', targetPrNumbers);
            core.setOutput('target_pr_numbers', JSON.stringify(targetPrNumbers));
        env:
          base_branch: ${{ steps.get_pr_details.outputs.base_branch }}
          merged_pr_number: ${{ steps.get_pr_details.outputs.merged_pr_number }}

      - name: Update Target PR Descriptions
        # 更新対象のPRが見つかった場合のみ実行
        if: steps.find_all_open_prs.outputs.target_pr_numbers != '[]'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const targetPrNumbers = JSON.parse(process.env.target_pr_numbers);
            const mergedDesignDocs = JSON.parse(process.env.design_docs);
            
            if (mergedDesignDocs.length === 0) {
              console.log('No design docs found in the merged PR. Skipping update for all target PRs.');
              return; // 設計書リンクが見つからなければ何もしない
            }

            for (const prNumber of targetPrNumbers) {
              try {
                // 対象PRの現在のDescriptionを取得
                const { data: targetPr } = await github.rest.pulls.get({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: prNumber,
                });

                let newTargetPrBody = targetPr.body || '';
                let existingDesignDocs = [];

                // 対象PRに既に「集約設計書一覧」セクションがあるかチェック
                const targetDocSectionMatch = newTargetPrBody.match(/#\s*集約設計書一覧\n([\s\S]*?)(?=\n#|\n---|$)/);
                if (targetDocSectionMatch && targetDocSectionMatch[1]) {
                  const links = targetDocSectionMatch[1].match(/\*\s*\[.*?\]\(https:\/\/docs\.google\.com\/spreadsheets\/d\/.*?\)/g);
                  if (links) {
                    existingDesignDocs = links.map(link => link.trim());
                  }
                }

                // マージされたPRのリンクを既存のリストに追加（重複は避ける）
                const allDesignDocs = [...new Set([...existingDesignDocs, ...mergedDesignDocs])];

                // 更新された設計書一覧セクションを生成
                let updatedDocSection = '# 集約設計書一覧\n\n' + allDesignDocs.join('\n');
                updatedDocSection += `\n\n---`; // 区切り線

                // 対象PRのDescriptionを更新
                if (targetDocSectionMatch) {
                  // 既存のセクションがあれば置き換える
                  newTargetPrBody = newTargetPrBody.replace(targetDocSectionMatch[0], updatedDocSection);
                } else {
                  // なければ追加する
                  newTargetPrBody += '\n\n' + updatedDocSection;
                }

                await github.rest.pulls.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: prNumber,
                  body: newTargetPrBody,
                });
                console.log(`Updated PR #${prNumber} with new design docs.`);
              } catch (error) {
                console.error(`Failed to update PR #${prNumber}: ${error.message}`);
              }
            }
        env:
          target_pr_numbers: ${{ steps.find_all_open_prs.outputs.target_pr_numbers }}
          design_docs: ${{ steps.get_pr_details.outputs.design_docs }} 
